In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn import metrics  
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier 

In [97]:
df=pd.read_csv('Titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [98]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [100]:
df.drop(columns=['Cabin'],inplace=True)
df.drop(columns=['PassengerId','Name','Ticket'],inplace=True)
df.dropna(inplace=True)

In [101]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [102]:
df.reset_index(drop=True,inplace=True)
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
707         0       3  female  39.0      0      5  29.1250        Q
708         0       2    male  27.0      0      0  13.0000        S
709         1       1  female  19.0      0      0  30.0000        S
710         1       1    male  26.0      0      0  30.0000        C
711         0       3    male  32.0      0      0   7.7500        Q

[712 rows x 8 columns]

In [103]:
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['Embarked']=le.fit_transform(df['Embarked'])

In [104]:
x=df.iloc[:,0:7]
y=df.iloc[:,-1]

In [105]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [106]:
model1 = tree.DecisionTreeClassifier(random_state=1)
model2 = RandomForestClassifier(n_estimators = 200)
model3 = KNeighborsClassifier(n_neighbors=7)
model = VotingClassifier(estimators=[('dt', model1), ('rf', model2), ('kn',model3)], voting='hard')

In [107]:
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8181818181818182

In [108]:
model1.fit(x_train,y_train)
model1.score(x_test,y_test)

0.8111888111888111

In [109]:
model2.fit(x_train,y_train)
model2.score(x_test,y_test)

0.7902097902097902

In [110]:
model3.fit(x_train,y_train)
model3.score(x_test,y_test)

0.7552447552447552

In [111]:
# Max voting result
y_pred=model.predict(x_test)
y_pred

array([2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1])

In [112]:
y_pred1=model1.predict_proba(x_test)
y_pred1

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [113]:
y_pred2=model2.predict_proba(x_test)
y_pred2

array([[0.        , 0.455     , 0.545     ],
       [0.        , 0.        , 1.        ],
       [0.01      , 0.        , 0.99      ],
       [0.        , 0.        , 1.        ],
       [0.36      , 0.        , 0.64      ],
       [0.52      , 0.        , 0.48      ],
       [0.52      , 0.        , 0.48      ],
       [0.02      , 0.11      , 0.87      ],
       [0.025     , 0.01      , 0.965     ],
       [0.4       , 0.        , 0.6       ],
       [0.        , 0.71      , 0.29      ],
       [0.64      , 0.005     , 0.355     ],
       [0.165     , 0.        , 0.835     ],
       [0.135     , 0.225     , 0.64      ],
       [0.035     , 0.        , 0.965     ],
       [0.25      , 0.        , 0.75      ],
       [0.03      , 0.        , 0.97      ],
       [0.175     , 0.02      , 0.805     ],
       [0.65      , 0.        , 0.35      ],
       [0.025     , 0.        , 0.975     ],
       [0.65      , 0.        , 0.35      ],
       [0.265     , 0.        , 0.735     ],
       [0.

In [114]:
y_pred3=model3.predict_proba(x_test)
y_pred3

array([[0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.14285714, 0.        , 0.85714286],
       [0.        , 0.14285714, 0.85714286],
       [0.42857143, 0.        , 0.57142857],
       [0.        , 0.        , 1.        ],
       [0.42857143, 0.        , 0.57142857],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.71428571, 0.        , 0.28571429],
       [0.        , 0.28571429, 0.71428571],
       [0.28571429, 0.        , 0.71428571],
       [0.28571429, 0.        , 0.71428571],
       [0.        , 0.        , 1.        ],
       [0.14285714, 0.        , 0.85714286],
       [0.        , 0.        , 1.        ],
       [0.14285714, 0.        , 0.85714286],
       [0.42857143, 0.        , 0.57142857],
       [0.14285714, 0.        , 0.85714286],
       [0.        , 0.        , 1.        ],
       [0.14285714, 0.        , 0.85714286],
       [0.14285714, 0.        , 0.85714286],
       [0.

directly for probablity of classes:

In [115]:
#Averaging
y_pred_avg=(y_pred1+y_pred2+y_pred3)/3
y_pred_avg

array([[0.        , 0.15166667, 0.84833333],
       [0.        , 0.        , 1.        ],
       [0.05095238, 0.        , 0.94904762],
       [0.        , 0.04761905, 0.95238095],
       [0.59619048, 0.        , 0.40380952],
       [0.50666667, 0.        , 0.49333333],
       [0.64952381, 0.        , 0.35047619],
       [0.00666667, 0.03666667, 0.95666667],
       [0.00833333, 0.00333333, 0.98833333],
       [0.37142857, 0.        , 0.62857143],
       [0.        , 0.6652381 , 0.3347619 ],
       [0.64190476, 0.00166667, 0.35642857],
       [0.1502381 , 0.        , 0.8497619 ],
       [0.045     , 0.075     , 0.88      ],
       [0.05928571, 0.        , 0.94071429],
       [0.08333333, 0.        , 0.91666667],
       [0.05761905, 0.        , 0.94238095],
       [0.53452381, 0.00666667, 0.45880952],
       [0.59761905, 0.        , 0.40238095],
       [0.00833333, 0.        , 0.99166667],
       [0.59761905, 0.        , 0.40238095],
       [0.13595238, 0.        , 0.86404762],
       [0.

In [116]:
# Weighted averaging
y_pred_wavg=(0.5*y_pred1+0.3*y_pred2+0.2*y_pred3)
y_pred_wavg

array([[0.        , 0.1365    , 0.8635    ],
       [0.        , 0.        , 1.        ],
       [0.03157143, 0.        , 0.96842857],
       [0.        , 0.02857143, 0.97142857],
       [0.69371429, 0.        , 0.30628571],
       [0.656     , 0.        , 0.344     ],
       [0.74171429, 0.        , 0.25828571],
       [0.006     , 0.033     , 0.961     ],
       [0.0075    , 0.003     , 0.9895    ],
       [0.26285714, 0.        , 0.73714286],
       [0.        , 0.77014286, 0.22985714],
       [0.74914286, 0.0015    , 0.24935714],
       [0.10664286, 0.        , 0.89335714],
       [0.0405    , 0.0675    , 0.892     ],
       [0.03907143, 0.        , 0.96092857],
       [0.075     , 0.        , 0.925     ],
       [0.03757143, 0.        , 0.96242857],
       [0.63821429, 0.006     , 0.35578571],
       [0.72357143, 0.        , 0.27642857],
       [0.0075    , 0.        , 0.9925    ],
       [0.72357143, 0.        , 0.27642857],
       [0.10807143, 0.        , 0.89192857],
       [0.

directly for classes:

In [117]:
Y_pred1=model1.predict(x_test)
Y_pred2=model2.predict(x_test)
Y_pred3=model3.predict(x_test)
Y_AVG=(Y_pred1+Y_pred2+Y_pred3)/3
Y_AVG

array([2.        , 2.        , 2.        , 2.        , 1.33333333,
       0.66666667, 0.66666667, 2.        , 2.        , 1.33333333,
       1.33333333, 0.66666667, 2.        , 2.        , 2.        ,
       2.        , 2.        , 1.33333333, 0.66666667, 2.        ,
       0.66666667, 2.        , 2.        , 0.66666667, 1.33333333,
       2.        , 2.        , 2.        , 2.        , 1.33333333,
       2.        , 0.66666667, 1.33333333, 2.        , 0.        ,
       2.        , 2.        , 2.        , 2.        , 0.66666667,
       2.        , 2.        , 2.        , 1.66666667, 2.        ,
       2.        , 2.        , 2.        , 2.        , 2.        ,
       2.        , 1.33333333, 1.33333333, 2.        , 2.        ,
       1.33333333, 2.        , 2.        , 2.        , 2.        ,
       2.        , 2.        , 2.        , 2.        , 2.        ,
       2.        , 1.33333333, 0.66666667, 2.        , 2.        ,
       2.        , 2.        , 2.        , 0.66666667, 1.33333

In [118]:
Y_WAVG=(0.5*Y_pred1+0.3*Y_pred2+0.2*Y_pred3)
Y_WAVG

array([2. , 2. , 2. , 2. , 1. , 0.4, 0.4, 2. , 2. , 1.6, 1.2, 0.4, 2. ,
       2. , 2. , 2. , 2. , 1. , 0.4, 2. , 0.4, 2. , 2. , 0.4, 1.2, 2. ,
       2. , 2. , 2. , 1.4, 2. , 1. , 1.2, 2. , 0. , 2. , 2. , 2. , 2. ,
       0.6, 2. , 2. , 2. , 1.5, 2. , 2. , 2. , 2. , 2. , 2. , 2. , 1. ,
       1.6, 2. , 2. , 1.4, 2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. ,
       2. , 1.6, 0.4, 2. , 2. , 2. , 2. , 2. , 0.4, 1. , 0.4, 0. , 2. ,
       2. , 2. , 2. , 2. , 2. , 2. , 0.4, 1.4, 0.4, 2. , 2. , 2. , 2. ,
       1. , 0. , 2. , 2. , 2. , 2. , 0.6, 2. , 2. , 2. , 1.6, 0.4, 2. ,
       2. , 2. , 0.4, 1. , 2. , 2. , 0. , 2. , 2. , 2. , 0.4, 2. , 2. ,
       2. , 0.4, 2. , 2. , 1.2, 2. , 2. , 2. , 2. , 2. , 1.4, 2. , 2. ,
       2. , 2. , 1.5, 2. , 1.5, 2. , 1. , 2. , 2. , 2. , 0.4, 2. , 1.2])